<?php


namespace app\controllers;

use app\src\pbx\utils\EntityService;
use Yii;

/**
 * Class ServController
 * Класс расширяет рест контроллер
 * @package app\controllers
 */
class ServController extends \yii\rest\Controller
{
    /**
     * Проверяет пройдет ли идентификатор доступа авторизации
     *
     * @return array
     */
    public function behaviors()
    {
        $authKey = 'A@asfd365^%@asfva';
        $auth = Yii::$app->request->bodyParams['auth'] ?? false;
        if(!$auth || $auth !== $authKey)
            die('forbidden 403');

        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * Возвращает метод  модели, которая инциализируется с параметрами в EntityService
     *
     * @param $entity
     * @return array|string
     */
    public function actionAddEntity($entity)
    {
        return EntityService::add($entity, Yii::$app->request->bodyParams);
    }

//    public function actionGetLog($sid)
//    {
//        new Phone('', []);
//        return Log::getLogData($sid);
//    }

    /**
     * дамп кастомных полей
     *
     * @param $sid
     * @return void
     */
    public function actionCustomFields($sid)
    {
        var_dump($this->setCustomFields('leads',array(
//                ['name' => 'sourcePhone', 'code' => 'PBX_SPN', 'type' => 'text']
                ['name' => 'Friendly Name', 'code' => 'PBX_SPFN', 'type' => 'text']
            )
        ));
    }
}
