<?php

namespace app\modules\api\controllers;

use app\controllers\AppController;
use Yii;
use yii\web\ForbiddenHttpException;


/**
 * Class AmoController
 * @package app\modules\api\controllers
 */
class AmoController extends AppController
{
    /**
     *  Функция врзвращает некоторые моды или поведения управления контента
     *
     * @throws ForbiddenHttpException
     * @return array
     */
    public function behaviors(): array
    {
        $this->checkAccess();
        return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * Функция проверяет имеет ли юзер доступ
     *
     * @throws ForbiddenHttpException
     * @return void
     */
    public function checkAccess()
    {
        if (null === (Yii::$app->request->headers['XAuthToken'] ?? null)
            || Yii::$app->request->headers['XAuthToken'] !== API_AUTH_KEY) {
            throw new ForbiddenHttpException('Forbidden');
        }
    }

}