<?php

namespace app\models;

use Yii;

/**
 * Class Model
 * Класс модель, базовый, но унаследован от юи модели
 *
 * @property int $id
 * @property string $sid
 * @property int $config_id
 * @property int $amo_sid
 * @property boolean $is_top
 *
 * @property Config $config
 * @package app\models
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * Возвращает название таблицы
     *
     * @return string
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * Правила валидации входных параметров
     *
     * @return array
     */
    public function rules()
    {
        return [
            [['config_id', 'amo_sid'], 'integer'],
            [['is_top'], 'boolean'],
            [['config_id'], 'exist', 'skipOnError' => true, 'targetClass' => Config::className(), 'targetAttribute' => ['config_id' => 'id']],
            [['sid'], 'unique'],
        ];
    }

    /**
     * Сеттит свойство is_top и сохраняет в бвзу
     *
     * @return void
     */
    public function afterFind()
    {
        $this->is_top = boolval($this->is_top);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * Названия валидационных входных параметров
     *
     * @return array
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'config_id' => 'Config ID',
            'amo_sid' => 'amo Sid',
        ];
    }

    /**
     * Gets query for [[Config]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getConfig()
    {
        return $this->hasOne(Config::className(), ['id' => 'config_id']);
    }
}
