<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $sid
 * @property int $config_id
 * @property int $amo_sid
 * @property boolean $is_top
 *
 * @property Config $config
 */
class User extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['config_id', 'amo_sid'], 'integer'],
            [['is_top'], 'boolean'],
            [['config_id'], 'exist', 'skipOnError' => true, 'targetClass' => Config::className(), 'targetAttribute' => ['config_id' => 'id']],
            [['sid'], 'unique'],
        ];
    }

    /**
     *
     */
    public function afterFind()
    {
        $this->is_top = boolval($this->is_top);
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'config_id' => 'Config ID',
            'amo_sid' => 'amo Sid',
        ];
    }

    /**
     * Gets query for [[Config]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getConfig()
    {
        return $this->hasOne(Config::className(), ['id' => 'config_id']);
    }
}
